name: laravel_rest_api_flutter
description: A package to interact with a Laravel REST API
version: 0.0.1
homepage: https://github.com/xefi/laravel-rest-api-flutter

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.2.0

flutter:
